### ISSUE TITLE
A commit is "ahead" of upstream/master but it was merged a year ago???

### ISSUE THREAD

**Issue by jamshark70** [supercollider-quarks/quarks#122]
I want to add a new quark.

https://github.com/supercollider-quarks/quarks/compare/master...jamshark70:quarks:topic/addWtSynth

First one: "[Add ddwSpeedLim to main directory](https://github.com/supercollider-quarks/quarks/commit/f673d82126f2160315543ca276fd7b094f4c1b63)"

This was merged in October 2021!

Somehow they have different SHAs.

Is this going to be a merge conflict?

Such a fuss for adding one line... anyway what should I do?

**Comment by jamshark70** [comment]
I ended up taking the nuclear option -- deleting my local repository and my fork, and re-cloning.

Every time I have to do that, I think, "git *almost* works... *almost*."

Anyway it's OK now.

**Comment by dyfer** [comment]
> Somehow they have different SHAs.

What are "they" in this case?

IIUC, the different SHAs can happen in a few cases, e.g. when squash-merging.

But what was the real issue? Were you unable to make a clean addition? [This one](https://github.com/supercollider-quarks/quarks/compare/master...jamshark70:quarks:topic/addWtSynth) looks fine.

Generally, fetching upstream, creating a new branch and making the change (addition) seems to work fine on my end...
